// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLXNqtI8rJX-gRkJbyXMraQnRf5nuq2wA',
    appId: '1:361949737940:web:160c0403113de54f8b9c41',
    messagingSenderId: '361949737940',
    projectId: 'notesapp-79475',
    authDomain: 'notesapp-79475.firebaseapp.com',
    storageBucket: 'notesapp-79475.firebasestorage.app',
    measurementId: 'G-MJJWGXVWQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA43RorD8vmq2mA1SPlOxsXl4fZp9kiJts',
    appId: '1:361949737940:android:fba7b31e76006d028b9c41',
    messagingSenderId: '361949737940',
    projectId: 'notesapp-79475',
    storageBucket: 'notesapp-79475.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC49Y_45jrTgAbqlEEKvtmp7M9Daa7m6Lk',
    appId: '1:361949737940:ios:deab201445b9f0dc8b9c41',
    messagingSenderId: '361949737940',
    projectId: 'notesapp-79475',
    storageBucket: 'notesapp-79475.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLXNqtI8rJX-gRkJbyXMraQnRf5nuq2wA',
    appId: '1:361949737940:web:d7ccb5f77dc5175f8b9c41',
    messagingSenderId: '361949737940',
    projectId: 'notesapp-79475',
    authDomain: 'notesapp-79475.firebaseapp.com',
    storageBucket: 'notesapp-79475.firebasestorage.app',
    measurementId: 'G-LQJEX8NWN7',
  );
}
